add CAAPI ship order and inventory history schemas
nterprise/api-docs pull request #121
Opened 2021-04-12 15:57 UTC by jcuozzo

2021-04-13 13:39 UTC, hwalpurgis approved these changes

2021-04-13 13:40 UTC, manchuck requested changes

2021-04-13 13:40 UTC, manchuck commented on data/docs/jekyll/api/caapi/oas_caapi.json
> +      "Inventory History": {
Having spaces can cause issues for some libs. You can set the title property if you want to display it differently

2021-04-13 13:40 UTC, manchuck commented on data/docs/jekyll/api/caapi/oas_caapi.json
> +      "Ship Order": {
Space here as well

2021-04-13 13:57 UTC, jcuozzo commented
@manchuck the file you referenced is auto-generated from
```
./bin/generate.js -do docs oas --api=caapi
```
The only code changed was in data/docs/oas/v1/oas_caapi.json.  And the case matches the existing key for `"Work Request"`.  Should I change all 3 to be PascalCase there?

2021-04-14 15:21 UTC, manchuck commented
@jcuozzo I can't remember but does updating to pascal case, cause the renderer to change to sentence case? If not then we can leave it if so then update

2021-04-14 15:38 UTC, jcuozzo commented
@manchuck it appears the script will not update PascalCase to Sentence case

2021-04-14 15:39 UTC, manchuck approved these changes

2021-04-14 15:48 UTC, merged